table! {
    gps (id, utc) {
        id -> Int8,
        vin -> Text,
        utc -> Timestamptz,
        alarm -> Int4,
        status -> Int4,
        lng -> Float4,
        lat -> Float4,
        offset_lng -> Float4,
        offset_lat -> Float4,
        altitude -> Int2,
        speed -> Float4,
        direction -> Int2,
        mileage -> Nullable<Float4>,
        oil_mass -> Nullable<Float4>,
        r_speed -> Nullable<Float4>,
        firm_alarm_id -> Nullable<Int2>,
        tire_pressure -> Nullable<Text>,
        carriage_temperature -> Nullable<Int2>,
        ext_signal -> Nullable<Int4>,
        io_status -> Nullable<Int2>,
        ad0 -> Nullable<Int2>,
        ad1 -> Nullable<Int2>,
        rssi -> Nullable<Int2>,
        gnss -> Nullable<Int2>,
        ext_data -> Nullable<Text>,
        ver -> Int2,
        created -> Timestamptz,
    }
}